# Generated by Django 4.2.3 on 2023-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('cart', '0004_rename_delivery_options_cart_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='inventory.product'),
        ),
    ]
