# Generated by Django 4.2.3 on 2023-07-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_payment_time_alter_payment_receipt_number'),
        ('order', '0005_rename_delivery_options_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.payment'),
        ),
    ]
